surl:
  cacheTime: 60
  cacheTimeUnit: SECONDS
  domain: http://localhost:8083/surl/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/short_url?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

  # Redis
  redis:
    host: localhost
    password:
    database: 0
    port: 6379

logging:
  config: classpath:logback-dev.xml

